export const loginFields = [
  {
    labelText: "Email",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Enter email",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Enter password",
  },
];
export const guestFields = [
  {
    labelText: "Unique Code",
    labelFor: "uniqueCode",
    id: "uniqueCode",
    name: "uniqueCode",
    type: "text",
    autoComplete: "uniqueCode",
    isRequired: true,
    placeholder: "Enter your unique code",
  },
  // {
  //   labelText: "Password",
  //   labelFor: "password",
  //   id: "password",
  //   name: "password",
  //   type: "password",
  //   autoComplete: "current-password",
  //   isRequired: true,
  //   placeholder: "Enter password",
  // },
];

export const resetPasswordField = [
  {
    labelText: "New Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Enter new password",
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirm-password",
    id: "confirmPassword",
    name: "confirm-password",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "Confirm password",
  },
];

export const passwordFields = [
  {
    labelText: "Current Password",
    labelFor: "current-password",
    id: "currentPassword",
    name: "currentPassword",
    type: "password",
    autoComplete: "currentPassword",
    isRequired: true,
    placeholder: "Enter your current password",
  },
  {
    labelText: "New Password",
    labelFor: "newPassword",
    id: "newPassword",
    name: "newPassword",
    type: "password",
    autoComplete: "newPassword",
    isRequired: true,
    placeholder: "Enter new password",
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirm-password",
    id: "confirmPassword",
    name: "confirmPassword",
    type: "password",
    autoComplete: "confirmPassword",
    isRequired: true,
    placeholder: "Re-enter the new password",
  },
];

export const profileFields = [
  {
    labelText: "First Name",
    labelFor: "first-name",
    id: "firstName",
    name: "firstName",
    type: "text",
    autoComplete: "firstName",
    isRequired: true,
    placeholder: "Enter your First Name",
  },
  {
    labelText: "Last Name",
    labelFor: "lastName",
    id: "lastName",
    name: "lastName",
    type: "text",
    autoComplete: "lastname",
    isRequired: true,
    placeholder: "Enter your Last Name",
  },
  {
    labelText: "Email",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: false,
    placeholder: "Enter your email",
    disabled: true,
  },
  {
    labelText: "Telephone",
    labelFor: "telephone",
    id: "telephone",
    name: "telephone",
    type: "phone",
    autoComplete: "telephone",
    isRequired: false,
    placeholder: "Your Telephone Number",
  },
];

export const userFields = [
  {
    labelText: "First Name",
    labelFor: "firstname",
    id: "firstname",
    name: "firstname",
    type: "text",
    autoComplete: "given-name",
    isRequired: true,
    placeholder: "First Name",
  },
  {
    labelText: "Last Name",
    labelFor: "lastname",
    id: "lastname",
    name: "lastname",
    type: "text",
    autoComplete: "family-name",
    isRequired: true,
    placeholder: "Last Name",
  },

  {
    labelText: "Email",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: false,
    placeholder: "Email",
  },
  {
    labelText: "Telephone",
    labelFor: "telephone",
    id: "telephone",
    name: "telephone",
    type: "phone",
    autoComplete: "telephone",
    isRequired: false,
    placeholder: "Telephone",
  },
  {
    labelText: "Father's Name",
    labelFor: "fatherName",
    id: "fatherName",
    name: "fatherName",
    type: "text",
    autoComplete: "fatherName",
    isRequired: true,
    placeholder: "Father Name",
  },
  {
    labelText: "Mother's Name",
    labelFor: "motherName",
    id: "motherName",
    name: "motherName",
    type: "text",
    autoComplete: "motherName",
    isRequired: true,
    placeholder: "Mother Name",
  },
  {
    labelText: "God Parent Name",
    labelFor: "godParent",
    id: "godParent",
    name: "godParent",
    type: "text",
    autoComplete: "godParent",
    isRequired: false,
    placeholder: "God Parent Name",
  },
];

export const registerFields = [
  {
    labelText: "Email",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Enter email",
  },
  {
    labelText: "Username",
    labelFor: "username",
    id: "username",
    name: "username",
    type: "text",
    autoComplete: "username",
    isRequired: true,
    placeholder: "Enter username",
  },
  {
    labelText: "Telephone Number",
    labelFor: "telephone",
    id: "telephone",
    name: "telephone",
    type: "text",
    autoComplete: "telephone",
    isRequired: true,
    placeholder: "Enter telephone",
  },
  {
    labelText: "Age",
    labelFor: "age",
    id: "age",
    name: "age",
    type: "number",
    autoComplete: "age",
    isRequired: false,
    placeholder: "Enter your age ",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Enter password",
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirm-password",
    id: "confirmPassword",
    name: "confirm-password",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "Confirm password",
  },
];

export const memberSacramentsFields = [
  {
    labelText: "Date of Birth",
    labelFor: "dob",
    id: "dob",
    name: "dob",
    type: "date",
    autoComplete: "dob",
    isRequired: true,
    placeholder: "Date of Birth",
  },
  {
    labelText: "Baptism Date",
    labelFor: "baptismDate",
    id: "baptismDate",
    name: "baptismDate",
    type: "date",
    autoComplete: "baptismDate",
    isRequired: false,
    placeholder: "Baptism Date",
  },
  {
    labelText: "Confirmation Date",
    labelFor: "confirmationDate",
    id: "confirmationDate",
    name: "confirmationDate",
    type: "date",
    autoComplete: "confirmationDate",
    isRequired: false,
    placeholder: "Confirmation Date",
  },
  {
    labelText: "Eucahrist Date",
    labelFor: "euchuristicDate",
    id: "euchuristicDate",
    name: "euchuristicDate",
    type: "date",
    autoComplete: "euchuristicDate",
    isRequired: false,
    placeholder: "Eucharist Date",
  },
  {
    labelText: "Marriage Date",
    labelFor: "marriageDate",
    id: "marriageDate",
    name: "marriageDate",
    type: "date",
    autoComplete: "marriageDate",
    isRequired: false,
    placeholder: "Marriage Date",
  },
];

export const massApplicationFields = [
  {
    labelText: "Unique Code",
    labelFor: "uniqueCode",
    id: "uniqueCode",
    name: "uniqueCode",
    type: "text",
    autoComplete: "uniqueCode",
    isRequired: true,
    placeholder: "Enter  unique code",
  },
  {
    labelText: "Mass Date",
    labelFor: "massDate",
    id: "massDate",
    name: "massDate",
    type: "date",
    autoComplete: "massDate",
    isRequired: true,
    placeholder: "Enter Mass Date",
  },
];

export const offeringAmountFields = [
  {
    labelText: "Years",
    labelFor: "years",
    id: "years",
    name: "years",
    type: "number",
    autoComplete: "years",
    isRequired: true,
    placeholder: "Enter Number of years",
  },
  {
    labelText: "Annual Offering Amount",
    labelFor: "offeringAmount",
    id: "offeringAmount",
    name: "offeringAmount",
    type: "number",
    autoComplete: "offeringAmount",
    isRequired: true,
    placeholder: "Enter Annual Offering Amount",
  },
];

export const parishInfoFields = [
  {
    labelText: "Diocese",
    labelFor: "diocese",
    id: "diocese",
    name: "diocese",
    type: "text",
    autoComplete: "diocese",
    isRequired: true,
    placeholder: "Enter Name of Diocese",
  },
  {
    labelText: "Parish Name",
    labelFor: "parishName",
    id: "parishName",
    name: "parishName",
    type: "text",
    autoComplete: "parishName",
    isRequired: true,
    placeholder: "Enter  parish name",
  },
  {
    labelText: "Offering Amount",
    labelFor: "offeringAmount",
    id: "offeringAmount",
    name: "offeringAmount",
    type: "number",
    autoComplete: "offeringAmount",
    isRequired: true,
    placeholder: "Enter offering amount",
  },
];
